const slides=[...document.querySelectorAll('.slide')], dots=[...document.querySelectorAll('[data-slide]')];let current=0;
function show(index){current=Math.max(0,Math.min(slides.length-1,index));slides.forEach((slide,i)=>{slide.hidden=i!==current;slide.classList.toggle('active',i===current)});dots.forEach((dot,i)=>{dot.classList.toggle('selected',i===current);if(i===current)dot.setAttribute('aria-current','step');else dot.removeAttribute('aria-current')});document.querySelector('#counter').textContent=`0${current+1} / 04`;document.querySelector('#prev').disabled=current===0;document.querySelector('#next').disabled=current===slides.length-1;window.scrollTo({top:0,behavior:'instant'})}
dots.forEach(dot=>dot.addEventListener('click',()=>show(Number(dot.dataset.slide))));document.querySelector('#prev').onclick=()=>show(current-1);document.querySelector('#next').onclick=()=>show(current+1);document.querySelector('[data-next]').onclick=()=>show(1);document.querySelector('.wordmark').onclick=e=>{e.preventDefault();show(0)};document.addEventListener('keydown',e=>{if(e.altKey||e.ctrlKey||e.metaKey)return;if(e.key==='ArrowRight'){e.preventDefault();show(current+1)}if(e.key==='ArrowLeft'){e.preventDefault();show(current-1)}});
const full=document.querySelector('#fullscreen');if(!document.fullscreenEnabled)full.hidden=true;full.onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{full.hidden=true}};document.addEventListener('fullscreenchange',()=>{full.innerHTML=document.fullscreenElement?'Quitter le plein écran ⛶':'Plein écran ⛶'});
let applause=0;document.querySelector('#applause').onclick=()=>{applause++;document.querySelector('#reaction').textContent=['Merci ! On remercie la 2PESQUET et notre troisième coéquipier : le bouton suivant.','Encore ? Danyal & Valentin en tournée : salle 102, salle 103…','À deux, on prend deux fois plus de temps pour quitter la scène.','Doucement, nos chevilles ne rentrent déjà plus sous la table.','Rappel : les applaudissements ne rajoutent pas de points. On a vérifié. Deux fois.'][(applause-1)%5];if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;for(let i=0;i<34;i++){let piece=document.createElement('i');piece.className='confetti';piece.style.left=Math.random()*100+'vw';piece.style.background=['#cfff50','#faf8f1','#171713'][i%3];piece.style.animationDelay=Math.random()*.4+'s';document.body.append(piece);setTimeout(()=>piece.remove(),2400)}};

const jokes=["Participation : excellente… quand la question est « qui veut sortir ? ».","Concentration : 100 %. Les cinq pour cent du temps où elle fonctionne.","Travail de groupe : Danyal dit « on commence ? », Valentin dit « vas-y ». Réunion terminée.","Organisation : l’un pensait que l’autre avait pris la feuille. Une vraie connexion.","Maths : deux cerveaux, quatre slides, et toujours une calculatrice.","À la question « vous avez compris ? », nos hochements de tête sont parfaitement synchronisés.","Un stylo pour deux. On appelle ça une économie collaborative.","Notre plan B ? Se regarder jusqu’à ce que l’autre parle."];
let jokeIndex=0;document.querySelector('#more-jokes').onclick=()=>{jokeIndex=(jokeIndex+1)%jokes.length;document.querySelector('#joke').textContent=jokes[jokeIndex]};
const seriousLines=["Erreur 404 : sérieux introuvable. Essayez après les vacances.","Connexion aux deux cerveaux… les deux serveurs sont à la cantine.","Mise à jour disponible. Durée estimée : jusqu’à la sonnerie.","Mode sérieux activé. Danyal et Valentin ont quitté la conversation."];let seriousIndex=0;document.querySelector('#serious').onclick=()=>{document.querySelector('#serious-message').textContent=seriousLines[seriousIndex++%seriousLines.length]};
